const ORDERSYNC_CHANNELS = {
  AUTH_BOOTSTRAP: 'ordersync-auth:bootstrap',
  AUTH_LOGIN: 'ordersync-auth:login',
  AUTH_LOGOUT: 'ordersync-auth:logout',
  AUTH_GET_SESSION_STATUS: 'ordersync-auth:get-session-status',
  AUTH_STATUS_EVENT: 'ordersync-auth:status',
  SHELL_GET_BOOTSTRAP_STATE: 'ordersync-shell:get-bootstrap-state',
  SHELL_LOGIN: 'ordersync-shell:login',
  SHELL_LOGOUT: 'ordersync-shell:logout',
  SHELL_SELECT_TENANT: 'ordersync-shell:select-tenant',
  SHELL_ENTER_WORKSPACE: 'ordersync-shell:enter-workspace',
  GET_SYNC_STATUS: 'ordersync:get-sync-status',
  TRIGGER_SYNC: 'ordersync:trigger-sync',
  GET_PENDING_COUNT: 'ordersync:get-pending-count',
  GET_LAST_SYNC_TIME: 'ordersync:get-last-sync-time',
  RETRY_SYNC_ISSUE: 'ordersync:retry-sync-issue',
  RETRY_SAFE_SYNC_ITEMS: 'ordersync:retry-safe-sync-items',
  LIST_PRODUCTS: 'ordersync:list-products',
  CREATE_PRODUCT: 'ordersync:create-product',
  UPDATE_PRODUCT: 'ordersync:update-product',
  DELETE_PRODUCT: 'ordersync:delete-product',
  LIST_CUSTOMERS: 'ordersync:list-customers',
  CREATE_CUSTOMER: 'ordersync:create-customer',
  UPDATE_CUSTOMER: 'ordersync:update-customer',
  DELETE_CUSTOMER: 'ordersync:delete-customer',
  LIST_EXPENSES: 'ordersync:list-expenses',
  CREATE_EXPENSE: 'ordersync:create-expense',
  DELETE_EXPENSE: 'ordersync:delete-expense',
  LIST_ORDERS: 'ordersync:list-orders',
  GET_ORDER_BY_ID: 'ordersync:get-order-by-id',
  CREATE_ORDER: 'ordersync:create-order',
  BULK_CREATE_ORDERS: 'ordersync:bulk-create-orders',
  CANCEL_ORDER: 'ordersync:cancel-order',
  CORRECT_ORDER: 'ordersync:correct-order',
  UPDATE_ORDER_STATUS: 'ordersync:update-order-status',
  CREATE_ORDER_SHIPMENT: 'ordersync:create-order-shipment',
  CHATBOT_ASK: 'ordersync-chatbot:ask',
  SYNC_STATUS_EVENT: 'ordersync:sync-status',
}

module.exports = {
  ORDERSYNC_CHANNELS,
}
